spring:
  datasource:
    driverClassName: com.mysql.jdbc.Driver
    url: jdbc:mysql://localhost:3306/TestDB
    username: root
    password: rootroot
  jpa:
    hibernate.ddl-auto: update
    generate-ddl: true
    show-sql: true
    properties:
      hibernate:
        current_session_context_class: org.springframework.orm.hibernate4.SpringSessionContext
  cache:
    ehcache:
      config: classpath:ehcache.xml
  mail:
     host: smtp.gmail.com
     username: weatheralertawesome
     password: WeatherAlert14
     properties:
       mail:
        smtp:
         auth: true
         starttls:
          enable: true
          required: true

  kafka:
    bootstrap-servers: localhost:9092

app:
  topic:
    foo: foo.t

logging:

  file: /Users/xchen/Downloads/app.log
  level:
    root: ALL
    org.springframework.web: ALL
    com.memorynotfound: ALL


