spring:
  datasource:
    driverClassName: com.mysql.jdbc.Driver
    url: jdbc:mysql://localhost:3306/TestDB
    username: root
    password: rootroot
  jpa:
    hibernate.ddl-auto: update
    generate-ddl: true
    show-sql: true
    properties:
      hibernate:
        current_session_context_class: org.springframework.orm.hibernate4.SpringSessionContext
  cache:
    ehcache:
      config: classpath:ehcache.xml


